sudo : required
language: generic
services:
  - docker
before_install:
  - docker build -t nmodem2k/multi-container -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI==true nmodem2k/multi-container   npm run test

after_success:
  - docker build -t nmodem2k/multi-client ./client
  - docker build -t nmodem2k/multi-nginx ./nginx
  - docker build -t nmodem2k/multi-server ./server
  - docker build -t nmodem2k/multi-worker ./worker
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker push nmodem2k/multi-client
  - docker push nmodem2k/multi-nginx
  - docker push nmodem2k/multi-server
  - docker push nmodem2k/multi-worker

